### ISSUE TITLE
Build fail with fail error 1.

### ISSUE THREAD

**Issue by hanshantao** [cxfksword/MPVKit#1]
我用的macOS 13.2.1 Xcode 14.2 版本build的时候最后会报错，请问你那边用的什么什么版本？
最后报错的日志信息：
/usr/bin/make distclean environment: [:] url: file:///Users/xxx/Documents/workspace/mpv/MPVKit/Script/FFmpeg/ios/scratch/arm64
make: *** No rule to make target `distclean'.  Stop.
/usr/bin/xcrun --sdk iphoneos --show-sdk-path environment: [:]
/Applications/Xcode-14.2.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk
/usr/bin/xcrun --sdk iphoneos --show-sdk-path environment: [:]
/Applications/Xcode-14.2.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk
/usr/bin/xcrun --sdk iphoneos --show-sdk-path environment: [:]
/Applications/Xcode-14.2.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk
/usr/bin/xcrun --sdk iphoneos --show-sdk-path environment: [:]
/Applications/Xcode-14.2.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk
/Users/xxx/Documents/workspace/mpv/MPVKit/Script/FFmpeg-n5.1.2/configure --prefix=/Users/xxx/Documents/workspace/mpv/MPVKit/Script/FFmpeg/ios/thin/arm64 --disable-armv5te --disable-armv6 --disable-armv6t2 --disable-bsfs --disable-bzlib --disable-gray --disable-iconv --disable-linux-perf --disable-xlib --disable-swscale-alpha --disable-symver --disable-small --enable-cross-compile --enable-gpl --enable-libxml2 --enable-nonfree --enable-runtime-cpudetect --enable-thumb --enable-version3 --pkg-config-flags=--static --enable-static --disable-shared --disable-doc --disable-htmlpages --disable-manpages --disable-podpages --disable-txtpages --enable-avcodec --enable-avformat --enable-avutil --enable-network --enable-swresample --enable-swscale --disable-devices --disable-outdevs --disable-indevs --disable-postproc --disable-d3d11va --disable-dxva2 --disable-vaapi --disable-vdpau --enable-videotoolbox --enable-audiotoolbox --disable-encoders --disable-decoders --enable-decoder=av1 --enable-decoder=dca --enable-decoder=flv --enable-decoder=h263 --enable-decoder=h263i --enable-decoder=h263p --enable-decoder=h264 --enable-decoder=hevc --enable-decoder=mjpeg --enable-decoder=mjpegb --enable-decoder=mpeg1video --enable-decoder=mpeg2video --enable-decoder=mpeg4 --enable-decoder=mpegvideo --enable-decoder=rv30 --enable-decoder=rv40 --enable-decoder=tscc --enable-decoder=wmv1 --enable-decoder=wmv2 --enable-decoder=wmv3 --enable-decoder=vc1 --enable-decoder=vp6 --enable-decoder=vp6a --enable-decoder=vp6f --enable-decoder=vp7 --enable-decoder=vp8 --enable-decoder=vp9 --enable-decoder=aac* --enable-decoder=ac3* --enable-decoder=alac* --enable-decoder=amr* --enable-decoder=ape --enable-decoder=cook --enable-decoder=dca --enable-decoder=dolby_e --enable-decoder=eac3* --enable-decoder=flac --enable-decoder=mp1* --enable-decoder=mp2* --enable-decoder=mp3* --enable-decoder=opus --enable-decoder=pcm* --enable-decoder=truehd --enable-decoder=vorbis --enable-decoder=wma* --enable-decoder=ass --enable-decoder=ccaption --enable-decoder=dvbsub --enable-decoder=dvdsub --enable-decoder=movtext --enable-decoder=pgssub --enable-decoder=srt --enable-decoder=ssa --enable-decoder=subrip --enable-decoder=webvtt --disable-muxers --enable-muxer=dash --enable-muxer=hevc --enable-muxer=mp4 --enable-muxer=m4v --enable-muxer=mov --enable-muxer=mpegts --enable-muxer=webm* --disable-demuxers --enable-demuxer=aac --enable-demuxer=ac3 --enable-demuxer=aiff --enable-demuxer=amr --enable-demuxer=ape --enable-demuxer=asf --enable-demuxer=ass --enable-demuxer=avi --enable-demuxer=caf --enable-demuxer=concat --enable-demuxer=dash --enable-demuxer=data --enable-demuxer=eac3 --enable-demuxer=flac --enable-demuxer=flv --enable-demuxer=h264 --enable-demuxer=hevc --enable-demuxer=hls --enable-demuxer=live_flv --enable-demuxer=loas --enable-demuxer=m4v --enable-demuxer=matroska --enable-demuxer=mov --enable-demuxer=mp3 --enable-demuxer=mpeg* --enable-demuxer=ogg --enable-demuxer=rm --enable-demuxer=rtsp --enable-demuxer=srt --enable-demuxer=vc1 --enable-demuxer=wav --enable-demuxer=webm_dash_manifest --enable-protocols --disable-protocol=bluray --disable-protocol=ffrtmpcrypt --disable-protocol=gopher --disable-protocol=icecast --disable-protocol=librtmp* --disable-protocol=libssh --disable-protocol=md5 --disable-protocol=mmsh --disable-protocol=mmst --disable-protocol=sctp --disable-protocol=subfile --disable-protocol=unix --disable-filters --enable-filter=aformat --enable-filter=amix --enable-filter=anull --enable-filter=aresample --enable-filter=areverse --enable-filter=asetrate --enable-filter=atempo --enable-filter=atrim --enable-filter=bwdif --enable-filter=estdif --enable-filter=format --enable-filter=fps --enable-filter=hflip --enable-filter=hwdownload --enable-filter=hwmap --enable-filter=hwupload --enable-filter=idet --enable-filter=null --enable-filter=overlay --enable-filter=palettegen --enable-filter=paletteuse --enable-filter=pan --enable-filter=rotate --enable-filter=scale --enable-filter=setpts --enable-filter=transpose --enable-filter=trim --enable-filter=vflip --enable-filter=volume --enable-filter=w3fdif --enable-filter=yadif --enable-filter=yadif_videotoolbox --disable-debug --enable-stripping --enable-optimizations --enable-neon --enable-asm --enable-pic --disable-indev=avfoundation --disable-outdev=audiotoolbox --enable-avdevice --disable-programs --enable-openssl --enable-libass --enable-filter=subtitles --enable-libfribidi --enable-libfreetype --target-os=darwin --arch=aarch64 --cpu=armv8 environment: ["LDFLAGS": "-arch arm64 -mios-version-min=13.0 -isysroot /Applications/Xcode-14.2.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk", "CPPFLAGS": "-arch arm64 -mios-version-min=13.0 -isysroot /Applications/Xcode-14.2.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk", "LC_CTYPE": "C", "CFLAGS": "-arch arm64 -mios-version-min=13.0 -isysroot /Applications/Xcode-14.2.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk", "CC": "/usr/bin/clang ", "CMAKE_OSX_ARCHITECTURES": "arm64", "PKG_CONFIG_PATH": "/Users/xxx/Documents/workspace/mpv/MPVKit/Script/freetype/ios/thin/arm64/lib/pkgconfig:/Users/xxx/Documents/workspace/mpv/MPVKit/Script/fribidi/ios/thin/arm64/lib/pkgconfig:/Users/xxx/Documents/workspace/mpv/MPVKit/Script/harfbuzz/ios/thin/arm64/lib/pkgconfig:/Users/xxx/Documents/workspace/mpv/MPVKit/Script/libass/ios/thin/arm64/lib/pkgconfig:/Users/xxx/Documents/workspace/mpv/MPVKit/Script/openssl/ios/thin/arm64/lib/pkgconfig:", "PATH": "/usr/local/opt/gnu-sed/libexec/gnubin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin", "CXXFLAGS": "-arch arm64 -mios-version-min=13.0 -isysroot /Applications/Xcode-14.2.0.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS16.2.sdk"] url: file:///Users/xxx/Documents/workspace/mpv/MPVKit/Script/FFmpeg/ios/scratch/arm64
The operation couldn’t be completed. (fail error 1.)

**Comment by aehlke** [comment]
@cxfksword does this project work?

**Comment by cxfksword** [comment]
has fixed build error
