### ISSUE TITLE
The iOS HDR rendering seems incorrect

### ISSUE THREAD

**Issue by blindwrite** [cxfksword/MPVKit#14]
Hello, I downloaded and ran this project on iOS, and it seems that the HDR rendering is not as I expected. Did I make any mistake?

The rendering I expected
![IMG_1138](https://github.com/cxfksword/MPVKit/assets/62744692/0a394085-89da-4d7e-a398-1e9b12ce4ebb)

The actual rendering
![IMG_1137](https://github.com/cxfksword/MPVKit/assets/62744692/140f5898-b15b-4f12-b197-6a7e26f0a7ea)

The test video file
https://github.com/blindwrite/FileHolder/raw/video_samples/Life_of_Pi_HDR_Sample.mp4

**Comment by bitxeno** [comment]
The default HDR `tone-mapping` of mpv will preserve more details but appear darker. If you don't like this style, you can modify the `tone-mapping` options to try another style.

**Comment by cxfksword** [comment]
The default HDR `tone-mapping` of mpv will preserve more details but looks more darker. If you don't like this style, you can modify the `tone-mapping` options to try another style.

**Comment by blindwrite** [comment]
Yes, I later found out it was related to tone mapping, but I forgot to close the issue. Thank you.
