### ISSUE TITLE
多次编译都失败了，能更新一个enable libsmbclient的版本吗？

### ISSUE THREAD

**Issue by huaibaobao2017** [cxfksword/MPVKit#16]

**Comment by huaibaobao2017** [comment]
Thank you for the update. After testing, SMB can be used, but it was found that there is no sound in the 5.1/7.1 audio track videos, and the memory usage is over 700m.

**Comment by cxfksword** [comment]
Does the 5.1/7.1 audio track work correctly with the previous version?

**Comment by huaibaobao2017** [comment]
> Does the 5.1/7.1 audio track work correctly with the previous version?

yes

**Comment by cxfksword** [comment]
I revert back the ffmpeg version, you can try again.

**Comment by huaibaobao2017** [comment]
> I revert back the ffmpeg version, you can try again.

it works! Thank you!
