### ISSUE TITLE
Crash in simulator when run av1 video using Metal API

### ISSUE THREAD

**Issue by v4to** [cxfksword/MPVKit#19]
Hello. When I try to play an av1 file in simulator using Metal API example i got a crash, on real device everything ok. Using OpenGL API example both simulator and real device run ok. Seems like issue with MoltenVK or what else?

<img width="272" alt="image" src="https://github.com/cxfksword/MPVKit/assets/13971025/dcf0d72f-9c2f-4f1d-ae87-dfad90ed58ed">
<img width="693" alt="image" src="https://github.com/cxfksword/MPVKit/assets/13971025/a9d2a6da-66c7-46c4-ae66-bf723463a6ad">
<img width="912" alt="image" src="https://github.com/cxfksword/MPVKit/assets/13971025/177ffb64-7657-4b3e-82bb-98382747f92e">

**Comment by cxfksword** [comment]
Metal API support only a patch version and does not officially support it yet. Encountering any issues is not strange.😂
