### ISSUE TITLE
The compiled versions (0.35.1-0.38.0) do not support HEVC hard decoding

### ISSUE THREAD

**Issue by huaibaobao2017** [cxfksword/MPVKit#26]

**Comment by huaibaobao2017** [comment]
Sorry, it seems that the 10bit YUV (P010) cannot be hard decoded, only the CPU can be soft decoded.

**Comment by cxfksword** [comment]
You can try playing it with IINA to see if hardware decoding is supported. If not, then mpv doesn't support it yet.
