### ISSUE TITLE
libsmbclient build failed

### ISSUE THREAD

**Issue by endpne** [cxfksword/MPVKit#28]
How to reproduce:
`swift run build enable-libsmbclient`

error log
```
No gnutls support for AES CFB8
No gnutls support for AES CMAC
no suitable FAM library found
Building without DMAPI support: no suitable DMAPI library found
Missing libtracker-sparql development files for Spotlight backend "tracker"
Missing libjansson development files for Spotlight backend "elasticsearch"
configure summary failed
```

**Comment by endpne** [comment]
Can you provide the complete compilation command in GitHub CI? Which dependencies need to be installed? The repository file is too large.

**Comment by cxfksword** [comment]
The script currently only works on Macbook. I will divide it when have free time.

**Comment by cxfksword** [comment]
New version has divide it to https://github.com/mpvkit/libsmbclient-build
