### ISSUE TITLE
Use case?

### ISSUE THREAD

**Issue by aehlke** [cxfksword/MPVKit#3]
Sorry for the naive question but how can this be used on iOS? Is IINA the only library on iOS or do you have any other pointers? Thanks.

**Comment by cxfksword** [comment]
You can refer to the [yattee](https://github.com/yattee/yattee) project. If you only want to add a simple player in the app, may be [KSPlayer](https://github.com/kingslay/KSPlayer) is a better choice.

**Comment by aehlke** [comment]
Thanks. Yattee is AGPL so I can't touch it for my use, I take this to mean MPVKit is intended for Yattee. I'll look into KSPlayer, did not find that one before and it's LGPL - much appreciated.

edit: Ah KSPlayer isn't MPV, unless I misunderstand something and MPVKit is usable with KSPlayer? The only non GPLv3/AGPL MPV project I've been able to find is https://github.com/alexmercerind/media_kit/ which is Flutter

Thanks for your time

**Comment by cxfksword** [comment]
KSPlayer is based on FFMPEG, and there is currently no open source use case for MPVKit. 
MPVKit is currently only suitable for learning libmpv.
