### ISSUE TITLE
M2 设备上无法编译

### ISSUE THREAD

**Issue by tingv** [cxfksword/MPVKit#4]
<img width="1092" alt="iShot_2023-08-03_11 44 32" src="https://github.com/cxfksword/MPVKit/assets/47696436/8d77523a-e6fb-480d-9d0b-e4f865010564">

M2 设备上无法编译，一开始就提示我安装 brew，但我确实已经安装过了。在 Intel 芯片设备上能编译
 
```
Building for debugging...
[3/3] Linking build
Build complete! (3.16s)
/bin/zsh -c which brew environment: [:]
brew not found
The operation couldn’t be completed. (fail error 1.)
You need to run the script first
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
```

**Comment by cxfksword** [comment]
你可以自己改下代码，把opt执行目录加到PATH中

**Comment by guyman624** [comment]
> 你可以自己改下代码，把opt执行目录加到PATH中

are you able to elaborate? I already see /opt/homebrew/bin in /Plugins/BuildFFMpeg/main.swift and I added it to ~/.zshrc

**Comment by cxfksword** [comment]
> > 你可以自己改下代码，把opt执行目录加到PATH中
> 
> are you able to elaborate? I already see /opt/homebrew/bin in /Plugins/BuildFFMpeg/main.swift and I added it to ~/.zshrc

I have added the default path, you can try using the new code to build.

**Comment by guyman624** [comment]
> I have added the default path, you can try using the new code to build.

this fixed that issue, now I have another issue but I will open a new issue.
