### ISSUE TITLE
make distclean fails for all

### ISSUE THREAD

**Issue by guyman624** [cxfksword/MPVKit#9]
Hello, I am having trouble building. All the make distcleans are failing due to 
```
/usr/bin/make distclean environment: ["PATH": "/usr/local/opt/gnu-sed/libexec/gnubin:/opt/homebrew/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"] url: file:///Users/admin/Downloads/MPVKITNEW/Script/openssl/ios/scratch/arm64
make: *** No rule to make target `distclean'.  Stop.
```

I have tested doing `/Users/admin/Downloads/MPVKITNEW/Script/openssl/ios/scratch/arm64` and running `make distclean` and it works fine.

https://github.com/cxfksword/MPVKit/blob/main/Plugins/BuildFFmpeg/main.swift#L161

I am wondering if my issue is related to the file:// prefix? I will do a bit more searching.

**Comment by cxfksword** [comment]
You can ignore this error, there is no need to execute `distclean` before `configure`, I will delete it later.
